
before_script: 
  - "ssh-keyscan -H -p 22 gitlab.mpi-magdeburg.mpg.de >> /root/.ssh/known_hosts"
  - "git submodule sync"
  - "git submodule init"
  - "git submodule update --recursive --init"

stages: 
  - python2
  - python3
  - octave  

#------Ubuntu 14.04-------

ubuntu1404-python2: 
  image: "local:ubuntu-trusty-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python2.sh"
    - "./ci-scripts/python/ubuntu-python2.sh"
  stage: python2

ubuntu1404-python3: 
  image: "local:ubuntu-trusty-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python3.sh"
    - "./ci-scripts/python/ubuntu-python3.sh"
  stage: python3

ubuntu1404-octave: 
  image: "local:ubuntu-trusty-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/octave/ubuntu-oct.sh"
    - "./ci-scripts/octave/ubuntu-oct.sh"
  stage: octave

#------Ubuntu 16.04-------

ubuntu1604-python2: 
  image: "local:ubuntu-xenial-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python2.sh"
    - "./ci-scripts/python/ubuntu-python2.sh"
  stage: python2

ubuntu1604-python3: 
  image: "local:ubuntu-xenial-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python3.sh"
    - "./ci-scripts/python/ubuntu-python3.sh"
  stage: python3

ubuntu1604-octave: 
  image: "local:ubuntu-xenial-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/octave/ubuntu-oct.sh"
    - "./ci-scripts/octave/ubuntu-oct.sh"
  stage: octave

#------Centos -------

centos7-python2: 
  image: "local:centos7-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/centos7-python2.sh"
    - "./ci-scripts/python/centos7-python2.sh"
  stage: python2

centos7-python3: 
  image: "local:centos7-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/centos7-python3.sh"
    - "./ci-scripts/python/centos7-python3.sh"
  stage: python3

centos7-octave: 
  image: "local:centos7-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/octave/centos7-oct.sh"
    - "./ci-scripts/octave/centos7-oct.sh"
  stage: octave

#------Opensuse421 -------

opensuse421-python2: 
  image: "local:opensuse-42-1-base"
  only: 
    - master
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/opensuse421-python2.sh"
    - "./ci-scripts/python/opensuse421-python2.sh"
  stage: python2

opensuse421-python3: 
  image: "local:opensuse-42-1-base"
  only: 
    - master
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/opensuse421-python3.sh"
    - "./ci-scripts/python/opensuse421-python3.sh"
  stage: python3


opensuse421-octave: 
  image: "local:opensuse-42-1-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/octave/opensuse421-oct.sh"
    - "./ci-scripts/octave/opensuse421-oct.sh"
  stage: octave

