
before_script: 
  - "ssh-keyscan -H -p 22 gitlab.mpi-magdeburg.mpg.de >> /root/.ssh/known_hosts"
  - "git submodule sync"
  - "git submodule init"
  - "git submodule update --recursive --init"

stages: 
  - python2
  - python3

#------Ubuntu 14.04-------

ubuntu1404-python2: 
  image: "local:ubuntu-trusty-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python2.sh"
    - "./ci-scripts/python/ubuntu-python2.sh"
  stage: python2

ubuntu1404-python3: 
  image: "local:ubuntu-trusty-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python3.sh"
    - "./ci-scripts/python/ubuntu-python3.sh"
  stage: python3

#------Ubuntu 16.04-------

ubuntu1604-python2: 
  image: "local:ubuntu-xenial-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python2.sh"
    - "./ci-scripts/python/ubuntu-python2.sh"
  stage: python2

ubuntu1604-python3: 
  image: "local:ubuntu-xenial-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/ubuntu-python3.sh"
    - "./ci-scripts/python/ubuntu-python3.sh"
  stage: python3


#------Centos -------

centos7-python2: 
  image: "local:centos7-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/centos7-python2.sh"
    - "./ci-scripts/python/centos7-python2.sh"
  stage: python2

centos7-python3: 
  image: "local:centos7-base"
  only: 
    - master
    - code-4-pub
    - /^behr.*$/
  script: 
    - "chmod u+x ci-scripts/python/centos7-python3.sh"
    - "./ci-scripts/python/centos7-python3.sh"
  stage: python3


#------Opensuse421 -------

opensuse421-python2: 
  image: "local:opensuse-42-1-base"
  only: 
    - master
    - /^behr.*$/
  script: 
    - "chmod u+x scripts/gitlab-ci/opensuse421-python2.sh"
    - "./scripts/gitlab-ci/opensuse421-python2.sh"
  stage: python2

opensuse421-python3: 
  image: "local:opensuse-42-1-base"
  only: 
    - master
    - /^behr.*$/
  script: 
    - "chmod u+x scripts/gitlab-ci/opensuse421-python3.sh"
    - "./scripts/gitlab-ci/opensuse421-python3.sh"
  stage: python3

